namespace: alikins
name: 2-invalid-4-galaxy-collection_ntp
version: 0.1.174
license:
  - MIT
description: NTP installation and configuration for Linux.
repository:
documentation:
homepage:
issues:
authors:
  - geerlingguy
tags:
  - system
  - ntp
  - date
  - time
  - timezone
readme: "README.md"
dependencies: {}
